/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleVotingSol from './SimpleVoting.sol/index.js';
export type { simpleVotingSol };
import type * as tokenizedVotingSol from './TokenizedVoting.sol/index.js';
export type { tokenizedVotingSol };
export * as factories from './factories/index.js';
export type { SimpleVoting } from './SimpleVoting.sol/SimpleVoting.js';
export { SimpleVoting__factory } from './factories/SimpleVoting.sol/SimpleVoting__factory.js';
export type { TokenizedVoting } from './TokenizedVoting.sol/TokenizedVoting.js';
export { TokenizedVoting__factory } from './factories/TokenizedVoting.sol/TokenizedVoting__factory.js';