/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleVoting } from './SimpleVoting.js';
export * as factories from './factories/index.js';
export { SimpleVoting__factory } from './factories/SimpleVoting__factory.js';