/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SimpleVotingInterface extends Interface {
    getFunction(nameOrSignature: "addOption" | "endAt" | "finalize" | "finalized" | "hasVoted" | "isOpen" | "leadingOption" | "name" | "options" | "owner" | "setName" | "startAt" | "tally" | "totalVotes" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Finalized" | "Voted"): EventFragment;

    encodeFunctionData(functionFragment: 'addOption', values: [string]): string;
encodeFunctionData(functionFragment: 'endAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalize', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalized', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isOpen', values?: undefined): string;
encodeFunctionData(functionFragment: 'leadingOption', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'options', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setName', values: [string]): string;
encodeFunctionData(functionFragment: 'startAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'tally', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVotes', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leadingOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'options', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tally', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace FinalizedEvent {
      export type InputTuple = [tally: BigNumberish[], timestamp: BigNumberish];
      export type OutputTuple = [tally: bigint[], timestamp: bigint];
      export interface OutputObject {tally: bigint[], timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [voter: AddressLike, option: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [voter: string, option: bigint, timestamp: bigint];
      export interface OutputObject {voter: string, option: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleVoting;
    waitForDeployment(): Promise<this>;

    interface: SimpleVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addOption: TypedContractMethod<
      [label: string, ],
      [void],
      'nonpayable'
    >
    

    
    endAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    finalize: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    finalized: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isOpen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    leadingOption: TypedContractMethod<
      [],
      [[bigint, bigint, boolean] & {index: bigint, count: bigint, tie: boolean }],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    options: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setName: TypedContractMethod<
      [newName: string, ],
      [void],
      'nonpayable'
    >
    

    
    startAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tally: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    totalVotes: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [optionIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addOption'): TypedContractMethod<
      [label: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalize'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalized'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOpen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'leadingOption'): TypedContractMethod<
      [],
      [[bigint, bigint, boolean] & {index: bigint, count: bigint, tie: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'options'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setName'): TypedContractMethod<
      [newName: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tally'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'totalVotes'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [optionIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Finalized'): TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;

    filters: {
      
      'Finalized(uint256[],uint256)': TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
      Finalized: TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
    

      'Voted(address,uint8,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    
    };
  }