/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SimpleVotingInterface extends Interface {
    getFunction(nameOrSignature: "addOption" | "ballotOf" | "commitEndAt" | "commitVote" | "endAt" | "finalize" | "finalized" | "isCommitPhase" | "isOpen" | "isRevealPhase" | "issuer" | "leadingOption" | "name" | "options" | "owner" | "revealVote" | "setName" | "startAt" | "tally" | "totalVotes"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Committed" | "Finalized" | "Voted"): EventFragment;

    encodeFunctionData(functionFragment: 'addOption', values: [string]): string;
encodeFunctionData(functionFragment: 'ballotOf', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'commitEndAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'commitVote', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'endAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalize', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalized', values?: undefined): string;
encodeFunctionData(functionFragment: 'isCommitPhase', values?: undefined): string;
encodeFunctionData(functionFragment: 'isOpen', values?: undefined): string;
encodeFunctionData(functionFragment: 'isRevealPhase', values?: undefined): string;
encodeFunctionData(functionFragment: 'issuer', values?: undefined): string;
encodeFunctionData(functionFragment: 'leadingOption', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'options', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'revealVote', values: [BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setName', values: [string]): string;
encodeFunctionData(functionFragment: 'startAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'tally', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVotes', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ballotOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitEndAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCommitPhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRevealPhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leadingOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'options', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revealVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tally', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVotes', data: BytesLike): Result;
  }

  
    export namespace CommittedEvent {
      export type InputTuple = [credentialHash: BytesLike, commitment: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [credentialHash: string, commitment: string, timestamp: bigint];
      export interface OutputObject {credentialHash: string, commitment: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FinalizedEvent {
      export type InputTuple = [tally: BigNumberish[], timestamp: BigNumberish];
      export type OutputTuple = [tally: bigint[], timestamp: bigint];
      export interface OutputObject {tally: bigint[], timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [credentialHash: BytesLike, option: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [credentialHash: string, option: bigint, timestamp: bigint];
      export interface OutputObject {credentialHash: string, option: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleVoting;
    waitForDeployment(): Promise<this>;

    interface: SimpleVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addOption: TypedContractMethod<
      [label: string, ],
      [void],
      'nonpayable'
    >
    

    
    ballotOf: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[string, boolean] & {commitment: string, revealed: boolean }],
      'view'
    >
    

    
    commitEndAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    commitVote: TypedContractMethod<
      [credentialHash: BytesLike, commitment: BytesLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    endAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    finalize: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    finalized: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isCommitPhase: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isOpen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isRevealPhase: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    issuer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    leadingOption: TypedContractMethod<
      [],
      [[bigint, bigint, boolean] & {index: bigint, count: bigint, tie: boolean }],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    options: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revealVote: TypedContractMethod<
      [credentialHash: BytesLike, optionIndex: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setName: TypedContractMethod<
      [newName: string, ],
      [void],
      'nonpayable'
    >
    

    
    startAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tally: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    totalVotes: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addOption'): TypedContractMethod<
      [label: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ballotOf'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[string, boolean] & {commitment: string, revealed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'commitEndAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'commitVote'): TypedContractMethod<
      [credentialHash: BytesLike, commitment: BytesLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalize'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalized'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isCommitPhase'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOpen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRevealPhase'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issuer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'leadingOption'): TypedContractMethod<
      [],
      [[bigint, bigint, boolean] & {index: bigint, count: bigint, tie: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'options'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revealVote'): TypedContractMethod<
      [credentialHash: BytesLike, optionIndex: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setName'): TypedContractMethod<
      [newName: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tally'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'totalVotes'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Committed'): TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
getEvent(key: 'Finalized'): TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;

    filters: {
      
      'Committed(bytes32,bytes32,uint256)': TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
      Committed: TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
    

      'Finalized(uint256[],uint256)': TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
      Finalized: TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
    

      'Voted(bytes32,uint8,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    
    };
  }