/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleVoting__factory } from './SimpleVoting__factory.js';
export { StakeToken__factory } from './StakeToken__factory.js';
export { TokenizedVoting__factory } from './TokenizedVoting__factory.js';