/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace SimpleVoting {
      
    export type ElectionMetadataStruct = {name: string, owner: AddressLike, issuer: AddressLike, startAt: BigNumberish, commitEndAt: BigNumberish, endAt: BigNumberish, phase: BigNumberish, finalized: boolean, optionCount: BigNumberish, totalVotes: BigNumberish}

    export type ElectionMetadataStructOutput = [name: string, owner: string, issuer: string, startAt: bigint, commitEndAt: bigint, endAt: bigint, phase: bigint, finalized: boolean, optionCount: bigint, totalVotes: bigint] & {name: string, owner: string, issuer: string, startAt: bigint, commitEndAt: bigint, endAt: bigint, phase: bigint, finalized: boolean, optionCount: bigint, totalVotes: bigint }
  
    }

  export interface SimpleVotingInterface extends Interface {
    getFunction(nameOrSignature: "VERSION" | "addOption" | "ballotOf" | "ballotStatus" | "ballotWeight" | "commitEndAt" | "commitVote" | "computeCommitment" | "credentialDigest" | "currentPhase" | "endAt" | "finalize" | "finalized" | "getOption" | "isCommitPhase" | "isCredentialRevoked" | "isOpen" | "isRevealPhase" | "issuer" | "leadingOption" | "metadata" | "optionCount" | "optionDetails" | "options" | "owner" | "proposalName" | "restoreCredential" | "revealVote" | "revokeCredential" | "setName" | "startAt" | "tally" | "totalVotes" | "verifyCredential"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Committed" | "CredentialRestoredEvent" | "CredentialRevokedEvent" | "Finalized" | "NameUpdated" | "OptionAdded" | "Voted"): EventFragment;

    encodeFunctionData(functionFragment: 'VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'addOption', values: [string]): string;
encodeFunctionData(functionFragment: 'ballotOf', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ballotStatus', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ballotWeight', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'commitEndAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'commitVote', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'computeCommitment', values: [BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'credentialDigest', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'currentPhase', values?: undefined): string;
encodeFunctionData(functionFragment: 'endAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalize', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalized', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOption', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isCommitPhase', values?: undefined): string;
encodeFunctionData(functionFragment: 'isCredentialRevoked', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isOpen', values?: undefined): string;
encodeFunctionData(functionFragment: 'isRevealPhase', values?: undefined): string;
encodeFunctionData(functionFragment: 'issuer', values?: undefined): string;
encodeFunctionData(functionFragment: 'leadingOption', values?: undefined): string;
encodeFunctionData(functionFragment: 'metadata', values?: undefined): string;
encodeFunctionData(functionFragment: 'optionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'optionDetails', values?: undefined): string;
encodeFunctionData(functionFragment: 'options', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposalName', values?: undefined): string;
encodeFunctionData(functionFragment: 'restoreCredential', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'revealVote', values: [BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'revokeCredential', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setName', values: [string]): string;
encodeFunctionData(functionFragment: 'startAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'tally', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVotes', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyCredential', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ballotOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ballotStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ballotWeight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitEndAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeCommitment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'credentialDigest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentPhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCommitPhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCredentialRevoked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRevealPhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leadingOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'metadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'optionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'optionDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'options', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'restoreCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revealVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tally', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCredential', data: BytesLike): Result;
  }

  
    export namespace CommittedEvent {
      export type InputTuple = [commitment: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [commitment: string, timestamp: bigint];
      export interface OutputObject {commitment: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CredentialRestoredEventEvent {
      export type InputTuple = [credentialHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [credentialHash: string, timestamp: bigint];
      export interface OutputObject {credentialHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CredentialRevokedEventEvent {
      export type InputTuple = [credentialHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [credentialHash: string, timestamp: bigint];
      export interface OutputObject {credentialHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FinalizedEvent {
      export type InputTuple = [tally: BigNumberish[], timestamp: BigNumberish];
      export type OutputTuple = [tally: bigint[], timestamp: bigint];
      export interface OutputObject {tally: bigint[], timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NameUpdatedEvent {
      export type InputTuple = [name: string];
      export type OutputTuple = [name: string];
      export interface OutputObject {name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OptionAddedEvent {
      export type InputTuple = [optionIndex: BigNumberish, label: string];
      export type OutputTuple = [optionIndex: bigint, label: string];
      export interface OutputObject {optionIndex: bigint, label: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [option: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [option: bigint, timestamp: bigint];
      export interface OutputObject {option: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleVoting;
    waitForDeployment(): Promise<this>;

    interface: SimpleVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    VERSION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addOption: TypedContractMethod<
      [label: string, ],
      [void],
      'nonpayable'
    >
    

    
    ballotOf: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[string, boolean] & {commitment: string, revealed: boolean }],
      'view'
    >
    

    
    ballotStatus: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[string, boolean, boolean] & {commitment: string, revealed: boolean, revoked: boolean }],
      'view'
    >
    

    
    ballotWeight: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    commitEndAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    commitVote: TypedContractMethod<
      [credentialHash: BytesLike, commitment: BytesLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    computeCommitment: TypedContractMethod<
      [credentialHash: BytesLike, optionIndex: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    credentialDigest: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [string],
      'view'
    >
    

    
    currentPhase: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    endAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    finalize: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    finalized: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    getOption: TypedContractMethod<
      [index: BigNumberish, ],
      [[string, bigint] & {label: string, votes: bigint }],
      'view'
    >
    

    
    isCommitPhase: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isCredentialRevoked: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    isOpen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isRevealPhase: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    issuer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    leadingOption: TypedContractMethod<
      [],
      [[bigint, bigint, boolean] & {index: bigint, count: bigint, tie: boolean }],
      'view'
    >
    

    
    metadata: TypedContractMethod<
      [],
      [SimpleVoting.ElectionMetadataStructOutput],
      'view'
    >
    

    
    optionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    optionDetails: TypedContractMethod<
      [],
      [[string[], bigint[]] & {labels: string[], counts: bigint[] }],
      'view'
    >
    

    
    options: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposalName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    restoreCredential: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    revealVote: TypedContractMethod<
      [credentialHash: BytesLike, optionIndex: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeCredential: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setName: TypedContractMethod<
      [newName: string, ],
      [void],
      'nonpayable'
    >
    

    
    startAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tally: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    totalVotes: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    verifyCredential: TypedContractMethod<
      [credentialHash: BytesLike, signature: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'VERSION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addOption'): TypedContractMethod<
      [label: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ballotOf'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[string, boolean] & {commitment: string, revealed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'ballotStatus'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[string, boolean, boolean] & {commitment: string, revealed: boolean, revoked: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'ballotWeight'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'commitEndAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'commitVote'): TypedContractMethod<
      [credentialHash: BytesLike, commitment: BytesLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'computeCommitment'): TypedContractMethod<
      [credentialHash: BytesLike, optionIndex: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'credentialDigest'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'currentPhase'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'endAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalize'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalized'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getOption'): TypedContractMethod<
      [index: BigNumberish, ],
      [[string, bigint] & {label: string, votes: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'isCommitPhase'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isCredentialRevoked'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOpen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRevealPhase'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issuer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'leadingOption'): TypedContractMethod<
      [],
      [[bigint, bigint, boolean] & {index: bigint, count: bigint, tie: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'metadata'): TypedContractMethod<
      [],
      [SimpleVoting.ElectionMetadataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'optionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'optionDetails'): TypedContractMethod<
      [],
      [[string[], bigint[]] & {labels: string[], counts: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'options'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposalName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'restoreCredential'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revealVote'): TypedContractMethod<
      [credentialHash: BytesLike, optionIndex: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeCredential'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setName'): TypedContractMethod<
      [newName: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tally'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'totalVotes'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifyCredential'): TypedContractMethod<
      [credentialHash: BytesLike, signature: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'Committed'): TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
getEvent(key: 'CredentialRestoredEvent'): TypedContractEvent<CredentialRestoredEventEvent.InputTuple, CredentialRestoredEventEvent.OutputTuple, CredentialRestoredEventEvent.OutputObject>;
getEvent(key: 'CredentialRevokedEvent'): TypedContractEvent<CredentialRevokedEventEvent.InputTuple, CredentialRevokedEventEvent.OutputTuple, CredentialRevokedEventEvent.OutputObject>;
getEvent(key: 'Finalized'): TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
getEvent(key: 'NameUpdated'): TypedContractEvent<NameUpdatedEvent.InputTuple, NameUpdatedEvent.OutputTuple, NameUpdatedEvent.OutputObject>;
getEvent(key: 'OptionAdded'): TypedContractEvent<OptionAddedEvent.InputTuple, OptionAddedEvent.OutputTuple, OptionAddedEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;

    filters: {
      
      'Committed(bytes32,uint256)': TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
      Committed: TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
    

      'CredentialRestoredEvent(bytes32,uint256)': TypedContractEvent<CredentialRestoredEventEvent.InputTuple, CredentialRestoredEventEvent.OutputTuple, CredentialRestoredEventEvent.OutputObject>;
      CredentialRestoredEvent: TypedContractEvent<CredentialRestoredEventEvent.InputTuple, CredentialRestoredEventEvent.OutputTuple, CredentialRestoredEventEvent.OutputObject>;
    

      'CredentialRevokedEvent(bytes32,uint256)': TypedContractEvent<CredentialRevokedEventEvent.InputTuple, CredentialRevokedEventEvent.OutputTuple, CredentialRevokedEventEvent.OutputObject>;
      CredentialRevokedEvent: TypedContractEvent<CredentialRevokedEventEvent.InputTuple, CredentialRevokedEventEvent.OutputTuple, CredentialRevokedEventEvent.OutputObject>;
    

      'Finalized(uint256[],uint256)': TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
      Finalized: TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
    

      'NameUpdated(string)': TypedContractEvent<NameUpdatedEvent.InputTuple, NameUpdatedEvent.OutputTuple, NameUpdatedEvent.OutputObject>;
      NameUpdated: TypedContractEvent<NameUpdatedEvent.InputTuple, NameUpdatedEvent.OutputTuple, NameUpdatedEvent.OutputObject>;
    

      'OptionAdded(uint256,string)': TypedContractEvent<OptionAddedEvent.InputTuple, OptionAddedEvent.OutputTuple, OptionAddedEvent.OutputObject>;
      OptionAdded: TypedContractEvent<OptionAddedEvent.InputTuple, OptionAddedEvent.OutputTuple, OptionAddedEvent.OutputObject>;
    

      'Voted(uint8,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    
    };
  }